[package]
name = "gen-color-elixizi"
version = "0.0.0"
authors = ["Miguel Verissimo", "rhysd <lin90162@yahoo.co.jp>"]
publish = false
edition = "2018"

[dependencies]
getopts = "0.2"
failure = "0.1"

[dev-dependencies]
regex = "1"
